### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Swiffany** [kleinzcy/SASSnet#10]
Hello,thank you for your excellent work! I have a question about the dataset:  the dataset download link u support in paper can't open ,do u share me another download link? thank u!  I am looking forward to your reply!

**Comment by kleinzcy** [comment]
Sorry, the dataset has been offlined by the owner. We do not have the download link.

**Comment by Swiffany** [comment]
> Sorry, the dataset has been offlined by the owner. We do not have the download link.

ok! I got it! thank u !
