### ISSUE TITLE
data

### ISSUE THREAD

**Issue by ryandok** [kleinzcy/SASSnet#2]
Your work is very good.I am very eager to download the data you use in your work.But the data can no longer be downloaded from the official website.Would you please share it with me?

**Comment by kleinzcy** [comment]
@ryandok  Sorry for the late reply.

According to the rule, I can't share the data. But, you can email the organizer of the competition for the data.

**Comment by ryandok** [comment]
It doesn’t matter. Thank you for your reply.



发自我的iPhone


------------------ Original ------------------
