### ISSUE TITLE
about the test 

### ISSUE THREAD

**Issue by 18677064404** [kleinzcy/SASSnet#4]
Dear author：

Hi, Thanks for your great work! I am interested in your work.
 
Sorry to disturb you.I have some questions. I downloaded the "2018 Atrial Segmentation Challenge COMPLETE DATASET",and then used the "la_heart_processing.py" file to process the "Training Set", and  put in in the corresponding directory，and the file “train_gan_sdfloss” work on, training success. But when I test with the train model "iter_6000.pth", the result showed :average metric is [ 0.18091923  0.10030632 53.18094769 23.59822443]. If I test with your "best.pth" it can get the same result as your paper showed.

Can you give me some answers? Thanks

Best wish!

**Comment by kleinzcy** [comment]
Sorry for the late reply and your attention. 

I have not encountered a situation like you. Maybe you can check if the training set is right by eval the training set, and you can also check the learning curve.

Best wish!

Klein
________________________________________
发件人: dawn_lan ***@***.***
发送时间: 2021年7月11日 15:50
收件人: kleinzcy/SASSnet
抄送: Subscribed
主题: [kleinzcy/SASSnet] about the test  (#4)

Dear author：

Hi, Thanks for your great work! I am interested in your work.

Sorry to disturb you.I have some questions. I downloaded the "2018 Atrial Segmentation Challenge COMPLETE DATASET",and then used the "la_heart_processing.py" file to process the "Training Set", and put in in the corresponding directory，and the file “train_gan_sdfloss” work on, training success. But when I test with the train model "iter_6000.pth", the result showed :average metric is [ 0.18091923 0.10030632 53.18094769 23.59822443]. If I test with your "best.pth" it can get the same result as your paper showed.

Can you give me some answers? Thanks

Best wish!

―

**Comment by 18677064404** [comment]
Thanks for your kindly reply.
Best wish!
