### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Swiffany** [kleinzcy/SASSnet#9]
Hello,thank you for your excellent work! I have a question about the dataset: what is the format for training and testing images in the data folder ? I am looking forward to your reply!

**Comment by kleinzcy** [comment]
You can modify the line 17 and 18 in https://github.com/kleinzcy/SASSnet/blob/master/code/dataloaders/la_heart.py, which defines the data path, to fit your case.

**Comment by Swiffany** [comment]
> You can modify the line 17 and 18 in https://github.com/kleinzcy/SASSnet/blob/master/code/dataloaders/la_heart.py, which defines the data path, to fit your case.

thank you for your reply!
